name: Release

on:
  push:
    tags:
      - "v*"
env:
  MONGODB_URI: ${{ vars.MONGODB_URI }}
  BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  JWT_SIGNING_PRIVATE_KEY: ${{ secrets.JWT_SIGNING_PRIVATE_KEY }}
  NISSIX_GITHUB_PRIVATE_KEY: ${{ secrets.NISSIX_GITHUB_PRIVATE_KEY }}
jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test


      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "**/dist/stats.json"

      - name: Publish npm packages
        run: yarn npm:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}