name: Create promotion pull request
on:
  push:
    branches:
      - master
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Version bump
        run: yarn version:bump
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: version bump
          title: Update Version
          branch: version-bump